<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-Amit" ignored="0" name="Test" tests="5" failures="2" timestamp="2022-07-29T17:30:44 IST" time="92.3" errors="0">
  <testcase name="validateLogin" time="9.058" classname="com.TestCases.LoginPageTest"/>
  <testcase name="validateLogin" time="8.774" classname="com.TestCases.LoginPageTest"/>
  <testcase name="validateloginpageTitle" time="0.006" classname="com.TestCases.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Page.LoginPage.gettitle(LoginPage.java:36)
at com.TestCases.LoginPageTest.validateloginpageTitle(LoginPageTest.java:40)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validateloginpageTitle -->
  <testcase name="Homenevigation" time="23.515" classname="com.TestCases.HomepageTest"/>
  <testcase name="validateLoginClick" time="0.003" classname="com.TestCases.HomepageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.TestCases.HomepageTest.validateLoginClick(HomepageTest.java:47)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginClick -->
</testsuite> <!-- Test -->
